Feature/git gist service
alexpahom/think-testguru pull request #13
Opened 2023-07-23 18:36 UTC by alexpahom

2023-07-24 05:42 UTC, VidgarVii requested changes

2023-07-24 05:42 UTC, VidgarVii commented on Gemfile
> +gem 'dotenv-rails'
данный гем используется только в дев окружении

2023-07-24 05:42 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    )
Гист создаётся, без входящих параметров от юзера, а с использованием хттп клиента. Соответственно если по каким-то причинам гист не был создан, то это уже баг в коде или сети. И видеть этот баг юзеру нет смысла. А следует разобраться и починить ошибку. Юзер всё-ровно ни чего исправить не сможет.

2023-07-24 05:42 UTC, VidgarVii commented on app/services/gist_question_service.rb
> +    Octokit::Client.new(access_token: ENV['GITHUB_TOKEN'])
если токена не будет. то ошибка будет на стороне октокит. Что не совсем корректно. Лучше проверку токена делать явной. Для этого можно воспользоваться  fetch
ENV.fetch('GITHUB_TOKEN')

2023-07-24 05:42 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +                      { notice: t('.success', link: result.url) }
ссылка на гист должна быть кликабельной

2023-07-24 05:42 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    gist = Gist.new(
если result.success? фолс, то нет смысла создавать Gist

2023-07-24 08:18 UTC, alexpahom commented on app/controllers/gists_controller.rb
> +    gist = Gist.new(
насколько я себе представляю, в выражении if result.success? && gist.save, если левая часть false, то правая выполнятся и не будет, а следовательно, в базу ничего не запишется

2023-07-24 13:21 UTC, VidgarVii requested changes

2023-07-24 13:21 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +    gist = Gist.new(
да так и есть. а зечем тогда создавать объект в памяти? И как я уже писал выше, если по каким-то причинам гист не запишется в бд при созданном гист в гитхабе, то это уже баг, который надо чинить. И лучше его выявить сразу. Тут стоит быть более строгим к своему коду и использовать bang! методы при записи в бд.

2023-07-24 13:24 UTC, VidgarVii requested changes

2023-07-24 13:24 UTC, VidgarVii commented on .gitignore
> +.env
секреты скрыты, это хорошо. Но другому разработчику надо понять какие ЕНВ нужны для проекта.
По этому надо добавить файл .env.example, который будет содержать пустые ЕНВ

2023-07-24 13:24 UTC, VidgarVii commented on .gitignore
> +.idea
так же стоит полностью удалить из репозитория файлы в .idea

2023-07-25 06:19 UTC, VidgarVii requested changes

2023-07-25 06:19 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +                      Gist.create(
так мы сразу не узнаем сохранён ли в бд гист. Я писал, что в таких случаях надо использовать bang! методы
https://github.com/alexpahom/think-testguru/pull/13#discussion_r1272256313

2023-07-25 06:19 UTC, VidgarVii commented on app/controllers/gists_controller.rb
> +                      {}
наверное тут нужен какой-нить алерт?

2023-07-25 10:11 UTC, merged