Feature/js
alexpahom/think-testguru pull request #14
Opened 2023-07-25 20:38 UTC by alexpahom

2023-07-26 06:54 UTC, VidgarVii requested changes

2023-07-26 06:54 UTC, VidgarVii commented on app/javascript/packs/global.js
> +document.addEventListener('turbolinks:load', () => {
данный файл сейчас содержит просто набор каких-то функций. Так не стоит группировать код. Мы модели и контроллеры не храним в 1 файле и не устраиваем свалку.
Что я предлагаю. Потренироваться в ООП и отделить функционал кода по файлам.
JS позволяет создавать классы и браузеры это понимают, пусть пока и без инкапсуляций, но уже хоть что-то.
По пробуй создать такой класс утилиту, который принимает html элемент. И далее пусть эта утилита работает только с этим элементов. Таким образом мы сможем пере использоваться утилиту сколько угодно раз с разными элементами без переписывания кода. И так вся логика функционала будет обёрнута в класс, а не просто болтаться где-то снаружи. 
http://old.code.mu/books/javascript/oop/

2023-07-26 06:54 UTC, VidgarVii commented on app/javascript/packs/global.js
> +    password && password.addEventListener('input', checkPasswordMatch)
тут подключены сразу 2 слушателя. Которые делают одно и тоже
Вообще операция addEventListener довольно-таки тяжелая для сайта. Их даже принято отключать когда больше не нужны.
В данном кейсе можно обойтись 1 вызовом addEventListener. Просто надо вешать на родительский элемент. Например на форму. А в js уже проверять какие поля изменились

2023-07-26 06:54 UTC, VidgarVii commented on app/javascript/packs/global.js
> +    const password = document.getElementById('password')
на каждое срабатывание событие происходит поиск элементов. Когда можно это делать 1 раз и не мучить ресурсы компьютера клиента

2023-07-28 09:51 UTC, vkurennov approved these changes

2023-07-29 14:29 UTC, merged