feature(assoc): add scopes and validations
alexpahom/think-testguru pull request #5
Opened 2023-07-09 12:34 UTC by alexpahom

2023-07-09 12:41 UTC, alexpahom commented on app/models/answer.rb
> +    errors.add(:answers) if question.answers.count >= 4
После вызова #create! или #save!, если ответов >=4, бросает
```
TRANSACTION (0.1ms)  begin transaction
(3.6ms)  SELECT COUNT(*) FROM "answers" WHERE "answers"."question_id" = ?  [["question_id", 174]]
TRANSACTION (0.5ms)  rollback transaction                                                                   
/home/alexpahom/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/activemodel-6.1.7.4/lib/active_model/
attribute_methods.rb:469:in `method_missing': undefined method `answers' for #<Answer id: nil, body: "two",
correct: false, question_id: 174, created_at: nil, updated_at: nil> (NoMethodError)
```
при этом сам #validate_answers_count отрабатывает без проблем, записывая в `errors` нужную информацию

2023-07-09 17:54 UTC, alexpahom commented on app/models/answer.rb
> +    errors.add(:answers) if question.answers.count >= 4
разобрался

2023-07-10 04:17 UTC, VidgarVii requested changes

2023-07-10 04:17 UTC, VidgarVii commented on app/models/answer.rb
> +  validate :validate_answers_count
надо указать в каких ситуациях мы должны использовать данную валидацию. Иначе кол-во ответов в вопросе, будет проверяться даже при редактировании ответа

2023-07-10 04:17 UTC, VidgarVii commented on app/models/test.rb
>                      .pluck(:title)
у скоупов есть важная особенность - они должны возвращать chainable объекты (объекты `ActiveRecord::Relation`)
благодаря этому с их использованием можно строить цепочки вызовов
скоупы можно чейнить с квери-методами  `ActiveRecord`, к примеру `where(level: ...).order(id: :desc).created_last_week ...`, с методами ассоциаций
квери-методы также возвращают объекты `ActiveRecord::Relation`
НО!
`pluck` вернет обычный массив, что нарушит эту конвенцию
поэтому, если скоуп должен вернуть объект или массив, но не `ActiveRecord::Relation`, то его лучше реализовывать обычными методами класса

здесь можно создать скоуп, который будет делать, к примеру, все кроме `pluck`
а при желании сохранить прежнюю функциональность можно оставить плюс к скоупу метод класса и уже в методе класса (из прошлого задания) убрать все запросы, вызвать этот скоуп и зачейнить его "плаком"

2023-07-10 14:51 UTC, merged